### PR TITLE
update get method to accept 2xx status

### PR DESCRIPTION
**Pull request by AarynSmith**
This PR allows the get method to accept any 200-299 status code.

The stats resource appears to return a 202 code when the daily status is being updated along with possibly incomplete data, and a "message" key containing "Calculating stats for this user. Check back later." and a "status" key of "pending_update", and "is_up_to_date" of false, however it is still a valid statistics, and could be used.

There is no "error" key returned in the object, as defined in the REST docs for wakatime, so It sounds like this should be an acceptable message.

### CODE REVIEW

**Comment by AarynSmith** [comment]
Also added environment specific testing, and updated the workflow. Not sure why your tests are failing, looks like the key in your secrets may be unauthorized. The test checks complete fine on my fork with my key.

**Comment by YouEclipse** [comment]
i'll see what's wrong and make the tests pass.  also sent a collaborator inviting of this repo to you.

**Comment by AarynSmith** [comment]
Thanks! I'll look into adding some of the other resources from wakatime also.

**Comment by YouEclipse** [comment]
thanks,i'm just start to debug on why tests not passed.will fix it soon

**Comment by YouEclipse** [comment]
I did nothing but it passed on master.  and i found the reason is  only the repo collaborators  can access the secret env variables.

**Comment by AarynSmith** [comment]
Ahh, good to know. That makes sense.

**Pull request merged**
